#!/usr/bin/env python3
"""Mock OpenClaw CLI for nexus_openclaw_role_runtime.py smoke tests."""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path

from mock_role_runtime import (
    write_quality_assessor_output,
    write_report_integrator_output,
    write_skill_tester_outputs,
    write_test_designer_outputs,
)


def create_artifact(report_dir: Path, role_id: str, pattern: str) -> str | None:
    if not pattern or pattern.startswith("("):
        return None
    if "*" in pattern:
        target = report_dir / pattern.replace("*", role_id)
    else:
        target = report_dir / pattern
    target.parent.mkdir(parents=True, exist_ok=True)
    suffix = target.suffix.lower()
    if suffix == ".json":
        payload = {"generatedBy": role_id, "artifact": pattern}
        target.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    else:
        target.write_text(f"# Generated by {role_id}\n\nArtifact: {pattern}\n", encoding="utf-8")
    return str(target)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    sub = parser.add_subparsers(dest="command", required=True)

    invoke = sub.add_parser("invoke")
    invoke.add_argument("--skill", required=True)
    invoke.add_argument("--message", required=True)
    invoke.add_argument("--channel", required=True)
    invoke.add_argument("--output", required=True)
    invoke.add_argument("--result", required=True)
    args = parser.parse_args(argv)

    output_path = Path(args.output)
    result_path = Path(args.result)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    result_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(f"# Mock OpenClaw Output\n\n{args.message}\n", encoding="utf-8")

    report_dir = os.environ.get("NEXUS_REPORT_DIR")
    role_id = os.environ.get("NEXUS_ROLE_ID", "unknown-role")
    created_file = None
    if report_dir:
        report_root = Path(report_dir)
        if role_id == "quality-assessor":
            created = write_quality_assessor_output(report_root, "openclaw-demo")
            created_file = created[0] if created else None
        elif role_id == "test-designer":
            created = write_test_designer_outputs(report_root, "openclaw-demo")
            created_file = created[0] if created else None
        elif role_id == "skill-tester":
            created = write_skill_tester_outputs(report_root, "openclaw-demo")
            created_file = created[0] if created else None
        elif role_id == "report-integrator":
            created = write_report_integrator_output(report_root, "openclaw-demo")
            created_file = created[0] if created else None
        else:
            missing_raw = os.environ.get("NEXUS_MISSING_DELIVERABLES", "[]")
            try:
                missing_deliverables = json.loads(missing_raw)
            except json.JSONDecodeError:
                missing_deliverables = []
            if not isinstance(missing_deliverables, list):
                missing_deliverables = []
            for item in missing_deliverables:
                created = create_artifact(report_root, role_id, str(item))
                if created and not created_file:
                    created_file = created
            if not created_file:
                created_file = create_artifact(report_root, role_id, "TEST-DESIGN.md")

    payload = {
        "status": "ok",
        "resultFile": created_file,
        "note": f"mock openclaw handled {role_id}",
    }
    result_path.write_text(json.dumps(payload, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(json.dumps(payload, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
